#!/bin/bash

test "$1" -lt 65536 -a "$1" -gt 0 2>/dev/null && PORT="$1" || PORT=8000
test -d "$2" && DIR="$2" || DIR="$PWD"

printf 'Serving %s on port %d\n' "$DIR" "$PORT"

# include "/etc/lighttpd/mime-types.conf"
lighttpd -D -f /dev/stdin <<EOF
dir-listing.activate = "enable"
server.modules = (
    "mod_access",
    "mod_accesslog",
    "mod_cgi",
    "mod_setenv"
)

cgi.assign = (
    ".sh" => "/usr/bin/bash",
    ".awk" => ""
)
cgi.limits = ( "write-timeout" => 15, "read-timeout" => 15, "tcp-fin-propagate" => "SIGTERM")
setenv.set-environment = ( "PATH" => "$PATH" )

server.document-root = "$DIR"
server.port = $PORT

EOF
# server.errorlog      = "/dev/stderr"
# accesslog.filename   = "/dev/stderr"